#%RAML 1.0 NamedExample
health-example:
  {
  "application_name" : "health-api",
  "application_version" : "1.0.0",
  "api_name" : "health-api",
  "environment" : "Sandbox",
  "status" : "running"
}

