#%RAML 1.0
title: DCH-Sitecore-SAPI
types: 
    searchRequestDataType: !include /datatype/request/searchdataType.raml
    searchResponseDatatype: !include /datatype/response/search-dataType.raml
    assetDatatype: !include /datatype/response/retrieve-asset-dataType.raml


   

/entities:
  /{assetid}:
    get:
      displayName: get assets by id
      description: endpoints to get assets one by one
      responses:
        200:
          body:
            application/json:
              type: assetDatatype[]
              example: !include /example/response/retrieve-asset-example.json 

    put:
      displayName: update asset url
      description: endpoint to update the asset url
      body:
        application/json:
            type: assetDatatype[]
            example: !include example/request/update-asset.json
      responses:
        200:
          body:
            application/json:
              type: assetDatatype[]
              example: !include example/response/update-example.json


                
/search:
  post:
    displayName: Add Assets
    description: search asset from sitecore
    body:
      application/json:
        type: searchRequestDataType
        example: !include /example/request/search-example.json
    responses:
          201:
                body:
                      application/json:
                            type: searchResponseDatatype
                            example: !include /example/response/search-example.json
                                      
          
    
   
    
                







                

